sudo: false
language: python
python:
    - "2.7"
# before_install will simply setup a conda enviroment for installing python packages, if you
# have project dependencies it's usually recommended to go this route
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda

install:
    - conda install --yes python="2.7" sphinx
    - pip install git+https://github.com/necrolyte2/travis-sphinx#egg=travis-sphinx

script:
    - travis-sphinx -s docs build

after_success:
    - travis-sphinx -p deploy
